---
title: 编译器错误 CS1017
ms.date: 07/20/2015
f1_keywords:
- CS1017
helpviewer_keywords:
- CS1017
ms.assetid: e0902e8a-b042-4711-a8a6-83456a3f88cb
ms.openlocfilehash: 165a8a0c9e67ada65dd4dab61026e22fb5f8bb07
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 08/19/2019
ms.locfileid: "69609450"
---
# <a name="compiler-error-cs1017"></a>编译器错误 CS1017
catch 子句不能跟在 try 语句的常规 catch 子句之后  
  
 不接受任何参数的 `catch` 块必须是一系列 `catch` 块中的最后一个。 有关异常的详细信息, 请参阅[异常和异常处理](../programming-guide/exceptions/index.md)。  
  
## <a name="example"></a>示例  
 下面的示例生成 CS1017：  
  
```csharp  
// CS1017.cs  
using System;  
  
namespace x  
{  
    public class b : Exception  
    {  
    }  
  
    public class a  
    {  
        public static void Main()  
        {  
            try  
            {  
            }  
  
            catch   // CS1017, must be last catch  
            {  
            }  
  
            catch(b)  
            {  
                throw;  
            }  
        }  
    }  
}  
```
