---
title: 编译器错误 CS1015
ms.date: 07/20/2015
f1_keywords:
- CS1015
helpviewer_keywords:
- CS1015
ms.assetid: 53179feb-e8be-41e0-bb0b-f7879e9fa613
ms.openlocfilehash: c1a94c6d15737986cd8d203e66d2828e02eefa95
ms.sourcegitcommit: 10986410e59ff29f2ec55c6759bde3eb4d1a00cb
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 05/31/2019
ms.locfileid: "66423148"
---
# <a name="compiler-error-cs1015"></a><span data-ttu-id="6a4c8-102">编译器错误 CS1015</span><span class="sxs-lookup"><span data-stu-id="6a4c8-102">Compiler Error CS1015</span></span>
<span data-ttu-id="6a4c8-103">应是对象、字符串或类类型</span><span class="sxs-lookup"><span data-stu-id="6a4c8-103">An object, string, or class type expected</span></span>  
  
 <span data-ttu-id="6a4c8-104">尝试将预定义的数据类型传入 [catch](../../csharp/language-reference/keywords/try-catch.md) 块。</span><span class="sxs-lookup"><span data-stu-id="6a4c8-104">An attempt was made to pass a predefined data type into a [catch](../../csharp/language-reference/keywords/try-catch.md) block.</span></span> <span data-ttu-id="6a4c8-105">仅派生自 <xref:System.Exception?displayProperty=nameWithType> 的数据类型可传入 `catch` 块。</span><span class="sxs-lookup"><span data-stu-id="6a4c8-105">Only data types that derive from <xref:System.Exception?displayProperty=nameWithType> can be passed into a `catch` block.</span></span> <span data-ttu-id="6a4c8-106">有关异常的详细信息，请参阅[异常和异常处理](../../csharp/programming-guide/exceptions/index.md)。</span><span class="sxs-lookup"><span data-stu-id="6a4c8-106">For more information on exceptions, see [Exceptions and Exception Handling](../../csharp/programming-guide/exceptions/index.md).</span></span>  
  
## <a name="example"></a><span data-ttu-id="6a4c8-107">示例</span><span class="sxs-lookup"><span data-stu-id="6a4c8-107">Example</span></span>  
 <span data-ttu-id="6a4c8-108">下面的示例生成 CS1015：</span><span class="sxs-lookup"><span data-stu-id="6a4c8-108">The following sample generates CS1015:</span></span>  
  
```csharp  
// CS1015.cs  
class Sample  
{  
    static void Main()  
    {  
        try   
        {  
        }  
        catch(int)   // CS1015, int is not derived from System.Exception  
        {  
        }  
    }  
}  
```
