---
title: 编译器错误 CS1626
ms.date: 07/20/2015
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
ms.openlocfilehash: 1263fbd4d6591b1f231e38400c680b549ba5654e
ms.sourcegitcommit: ccd8c36b0d74d99291d41aceb14cf98d74dc9d2b
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 12/10/2018
ms.locfileid: "56797323"
---
# <a name="compiler-error-cs1626"></a><span data-ttu-id="f6b0b-102">编译器错误 CS1626</span><span class="sxs-lookup"><span data-stu-id="f6b0b-102">Compiler Error CS1626</span></span>
<span data-ttu-id="f6b0b-103">无法在包含 catch 子句的 Try 块体中生成值</span><span class="sxs-lookup"><span data-stu-id="f6b0b-103">Cannot yield a value in the body of a try block with a catch clause</span></span>  
  
 <span data-ttu-id="f6b0b-104">如果有一个 catch 子句与 try 块关联，该 try 块内不允许有 yield 语句。</span><span class="sxs-lookup"><span data-stu-id="f6b0b-104">A yield statement is not allowed in a try block if there is a catch clause associated with the try block.</span></span> <span data-ttu-id="f6b0b-105">若要避免此错误，请将 yield 语句从 try/catch/finally 块，或者删除 catch 块。</span><span class="sxs-lookup"><span data-stu-id="f6b0b-105">To avoid this error, either move the yield statement out of the try/catch/finally block, or remove the catch block.</span></span>
  
 <span data-ttu-id="f6b0b-106">下面的示例生成 CS1626：</span><span class="sxs-lookup"><span data-stu-id="f6b0b-106">The following sample generates CS1626:</span></span>  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
      finally
      {
      
      }
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
