---
title: Catch 块永远不会到达;<exception>已在上面处理同一个 Try 语句
ms.date: 07/20/2015
f1_keywords:
- bc42031
- vbc42031
helpviewer_keywords:
- BC42031
ms.assetid: 7d15597c-5988-42ea-a853-63cbf78faaf3
ms.openlocfilehash: e05a324e67f279c650626833a6745f28df388c0d
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 04/28/2019
ms.locfileid: "64627207"
---
# <a name="catch-block-never-reached-exception-handled-above-in-the-same-try-statement"></a><span data-ttu-id="95cc7-102">Catch 块永远不会到达;\<异常 > 已在上面处理同一个 Try 语句</span><span class="sxs-lookup"><span data-stu-id="95cc7-102">'Catch' block never reached; \<exception> handled above in the same 'Try' statement</span></span>
<span data-ttu-id="95cc7-103">无法达到代码中的 `Catch` 块，因为它已经在前面的 `Try` 块中得到处理。</span><span class="sxs-lookup"><span data-stu-id="95cc7-103">A `Catch` block in the code cannot be reached because it is handled in a preceding `Try` block.</span></span>  
  
<span data-ttu-id="95cc7-104">默认情况下，此消息是一个警告。</span><span class="sxs-lookup"><span data-stu-id="95cc7-104">By default, this message is a warning.</span></span> <span data-ttu-id="95cc7-105">若要深入了解如何隐藏警告或将警告视为错误，请参阅 [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic)。</span><span class="sxs-lookup"><span data-stu-id="95cc7-105">For more information about hiding warnings or treating warnings as errors, see [Configuring Warnings in Visual Basic](/visualstudio/ide/configuring-warnings-in-visual-basic).</span></span>
  
 <span data-ttu-id="95cc7-106">**错误 ID:** BC42031</span><span class="sxs-lookup"><span data-stu-id="95cc7-106">**Error ID:** BC42031</span></span>  
  
## <a name="to-correct-this-error"></a><span data-ttu-id="95cc7-107">更正此错误</span><span class="sxs-lookup"><span data-stu-id="95cc7-107">To correct this error</span></span>  
  
- <span data-ttu-id="95cc7-108">删除多余的语句。</span><span class="sxs-lookup"><span data-stu-id="95cc7-108">Remove the redundant statement.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="95cc7-109">请参阅</span><span class="sxs-lookup"><span data-stu-id="95cc7-109">See also</span></span>

- [<span data-ttu-id="95cc7-110">如何使用 try/catch 块来捕获异常</span><span class="sxs-lookup"><span data-stu-id="95cc7-110">How to use the try/catch block to catch exceptions</span></span>](../../standard/exceptions/how-to-use-the-try-catch-block-to-catch-exceptions.md)
- [<span data-ttu-id="95cc7-111">使用用户筛选的异常处理程序</span><span class="sxs-lookup"><span data-stu-id="95cc7-111">Using User-Filtered Exception Handlers</span></span>](../../standard/exceptions/using-user-filtered-exception-handlers.md)
- [<span data-ttu-id="95cc7-112">Try...Catch...Finally 语句</span><span class="sxs-lookup"><span data-stu-id="95cc7-112">Try...Catch...Finally Statement</span></span>](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
