---
title: 编译器错误 CS0103
ms.date: 07/20/2015
f1_keywords:
- CS0103
helpviewer_keywords:
- CS0103
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
ms.openlocfilehash: d1e9e93e78b493810512bc9f94a9a0d9e4db8e91
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 08/19/2019
ms.locfileid: "69604032"
---
# <a name="compiler-error-cs0103"></a><span data-ttu-id="5e3aa-102">编译器错误 CS0103</span><span class="sxs-lookup"><span data-stu-id="5e3aa-102">Compiler Error CS0103</span></span>
<span data-ttu-id="5e3aa-103">当前上下文中不存在名称“identifier”</span><span class="sxs-lookup"><span data-stu-id="5e3aa-103">The name 'identifier' does not exist in the current context</span></span>  
  
 <span data-ttu-id="5e3aa-104">尝试了使用类、[命名空间](../keywords/namespace.md)或范围中不存在的名称。</span><span class="sxs-lookup"><span data-stu-id="5e3aa-104">An attempt was made to use a name that does not exist in the class, [namespace](../keywords/namespace.md), or scope.</span></span> <span data-ttu-id="5e3aa-105">检查名称的拼写，并检查 using 指令和程序集引用，确保您尝试使用的名称可用。</span><span class="sxs-lookup"><span data-stu-id="5e3aa-105">Check the spelling of the name and check your using directives and assembly references to make sure that the name that you are trying to use is available.</span></span>  
  
 <span data-ttu-id="5e3aa-106">如果在循环或者 `try` 或 `if` 块中声明一个变量，然后尝试从封闭代码块或独立代码块访问此变量，通常就会发生此错误，如下面的示例所示。</span><span class="sxs-lookup"><span data-stu-id="5e3aa-106">This error frequently occurs if you declare a variable in a loop or a `try` or `if` block and then attempt to access it from an enclosing code block or a separate code block, as shown in the following example.</span></span>  
  
```csharp  
using System;  
  
class MyClass1  
{  
    public static void Main()  
    {  
        try  
        {  
            // The following declaration is only available inside the try block.  
            MyClass1 conn = new MyClass1();  
        }  
        catch (Exception e)  
        {  
            // The following expression causes error CS0103, because variable  
            // conn only exists in the try block.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```  
  
 <span data-ttu-id="5e3aa-107">下面的示例解决了这一错误。</span><span class="sxs-lookup"><span data-stu-id="5e3aa-107">The following example resolves the error.</span></span>  
  
```csharp  
using System;  
  
class MyClass2  
{  
    public static void Main()  
    {  
        // To resolve the error in the example, the first step is to   
        // move the declaration of conn out of the try block. The following  
        // declaration is available throughout the Main method.  
        MyClass2 conn = null;  
        try  
        {  
            // Inside the try block, use the conn variable that you declared  
            // previously.  
            conn = new MyClass2();  
        }  
        catch (Exception e)  
        {  
            // The following expression no longer causes an error, because  
            // the declaration of conn is in scope.  
            if (conn != null)   
                Console.WriteLine("{0}", e);  
        }  
    }  
}  
```
